///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace smokeTest
{
    public partial class AddProModules
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Set_Value_ModuleType3(RepoItemInfo selecttagInfo)
        {
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '3' on item 'selecttagInfo'.", selecttagInfo);
            selecttagInfo.FindAdapter<SelectTag>().Element.SetAttributeValue("TagValue", "3");
        }

        public void Set_Value_ModuleType2(RepoItemInfo selecttagInfo)
        {
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '2' on item 'selecttagInfo'.", selecttagInfo);
            selecttagInfo.FindAdapter<SelectTag>().Element.SetAttributeValue("TagValue", "2");
        }

        public void Set_Value_ModuleType1(RepoItemInfo selecttagInfo)
        {
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '1' on item 'selecttagInfo'.", selecttagInfo);
            selecttagInfo.FindAdapter<SelectTag>().Element.SetAttributeValue("TagValue", "1");
        }

        public void Set_Value_ModuleType(RepoItemInfo selecttagInfo)
        {
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '7' on item 'selecttagInfo'.", selecttagInfo);
            selecttagInfo.FindAdapter<SelectTag>().Element.SetAttributeValue("TagValue", "7");
        }

        public void Mouse_Click_AddNewIOModule(RepoItemInfo buttontagInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttontagInfo' at 69;19.", buttontagInfo);
            buttontagInfo.FindAdapter<ButtonTag>().Click("69;19");
        }

        public void Mouse_Click_NavDeviceSettingsIoModules(RepoItemInfo atagInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'atagInfo' at 95;16.", atagInfo);
            atagInfo.FindAdapter<ATag>().Click("95;16");
        }

    }
}
