///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace smokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The allFields recording.
    /// </summary>
    [TestModule("121ac81b-73e2-49c3-a804-e2397308ed97", ModuleType.Recording, 1)]
    public partial class allFields : ITestModule
    {
        /// <summary>
        /// Holds an instance of the smokeTestRepository repository.
        /// </summary>
        public static smokeTestRepository repo = smokeTestRepository.Instance;

        static allFields instance = new allFields();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public allFields()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static allFields Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Http192168250188ApiReportApiGe.AVLAVView' at 474;9.", repo.Http192168250188ApiReportApiGe.AVLAVViewInfo, new RecordItemIndex(0));
            repo.Http192168250188ApiReportApiGe.AVLAVView.Click("474;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Http192168250188ApiReportApiGe.RegisterkarteSchliessenStrgPlusW' at 7;7.", repo.Http192168250188ApiReportApiGe.RegisterkarteSchliessenStrgPlusWInfo, new RecordItemIndex(1));
            repo.Http192168250188ApiReportApiGe.RegisterkarteSchliessenStrgPlusW.Click("7;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InternetExplorer' at 6;11.", repo.InternetExplorer.SelfInfo, new RecordItemIndex(2));
            repo.InternetExplorer.Self.Click("6;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InternetExplorer.ButtonDieAktuelleRegisterkarteSchlies' at 35;15.", repo.InternetExplorer.ButtonDieAktuelleRegisterkarteSchliesInfo, new RecordItemIndex(3));
            repo.InternetExplorer.ButtonDieAktuelleRegisterkarteSchlies.Click("35;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InternetExplorer.InternetExplorer' at 88;20.", repo.InternetExplorer.InternetExplorerInfo, new RecordItemIndex(4));
            repo.InternetExplorer.InternetExplorer.Click("88;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InternetExplorer' at 8;118.", repo.InternetExplorer.SelfInfo, new RecordItemIndex(5));
            repo.InternetExplorer.Self.Click("8;118");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InternetExplorer.ButtonDieAktuelleRegisterkarteSchlies' at 35;12.", repo.InternetExplorer.ButtonDieAktuelleRegisterkarteSchliesInfo, new RecordItemIndex(6));
            repo.InternetExplorer.ButtonDieAktuelleRegisterkarteSchlies.Click("35;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
