///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace smokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DataExportProfilePDF recording.
    /// </summary>
    [TestModule("6d57c504-40c3-4867-a26e-a47971164290", ModuleType.Recording, 1)]
    public partial class DataExportProfilePDF : ITestModule
    {
        /// <summary>
        /// Holds an instance of the smokeTestRepository repository.
        /// </summary>
        public static smokeTestRepository repo = smokeTestRepository.Instance;

        static DataExportProfilePDF instance = new DataExportProfilePDF();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DataExportProfilePDF()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DataExportProfilePDF Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.NavMonitorIndex' at 72;20.", repo.ElproMONITORLogin.NavMonitorIndexInfo, new RecordItemIndex(0));
            repo.ElproMONITORLogin.NavMonitorIndex.Click("72;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.NavDeviceSettingsIndex' at 80;24.", repo.ElproMONITORLogin.NavDeviceSettingsIndexInfo, new RecordItemIndex(1));
            repo.ElproMONITORLogin.NavDeviceSettingsIndex.Click("80;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.NavProfilesDataExportProfiles' at 101;13.", repo.ElproMONITORLogin.NavProfilesDataExportProfilesInfo, new RecordItemIndex(2));
            repo.ElproMONITORLogin.NavProfilesDataExportProfiles.Click("101;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ElproMONITORLogin.ContentCenter.AddNewProfile'.", repo.ElproMONITORLogin.ContentCenter.AddNewProfileInfo, new RecordItemIndex(3));
            Validate.Exists(repo.ElproMONITORLogin.ContentCenter.AddNewProfileInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.ContentCenter.AddNewProfile' at 27;17.", repo.ElproMONITORLogin.ContentCenter.AddNewProfileInfo, new RecordItemIndex(4));
            repo.ElproMONITORLogin.ContentCenter.AddNewProfile.Click("27;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.Name' at 197;19.", repo.ElproMONITORLogin.NameInfo, new RecordItemIndex(5));
            repo.ElproMONITORLogin.Name.Click("197;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.Name' at 232;19.", repo.ElproMONITORLogin.NameInfo, new RecordItemIndex(6));
            repo.ElproMONITORLogin.Name.Click("232;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'PDF-Profile' with focus on 'ElproMONITORLogin.Name'.", repo.ElproMONITORLogin.NameInfo, new RecordItemIndex(7));
            repo.ElproMONITORLogin.Name.PressKeys("PDF-Profile");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ElproMONITORLogin.MshtmlHTMLInputElementClass.SomeLiTag'.", repo.ElproMONITORLogin.MshtmlHTMLInputElementClass.SomeLiTagInfo, new RecordItemIndex(8));
            Validate.Exists(repo.ElproMONITORLogin.MshtmlHTMLInputElementClass.SomeLiTagInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ElproMONITORLogin.MshtmlHTMLInputElementClass.RequestButtonLeft'.", repo.ElproMONITORLogin.MshtmlHTMLInputElementClass.RequestButtonLeftInfo, new RecordItemIndex(9));
            Validate.Exists(repo.ElproMONITORLogin.MshtmlHTMLInputElementClass.RequestButtonLeftInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.ExportToPdf' at 9;11.", repo.ElproMONITORLogin.ExportToPdfInfo, new RecordItemIndex(10));
            repo.ElproMONITORLogin.ExportToPdf.Click("9;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.OptionTagPercentScheduleTaskNamePercent' at 56;9.", repo.ElproMONITORLogin.OptionTagPercentScheduleTaskNamePercentInfo, new RecordItemIndex(11));
            repo.ElproMONITORLogin.OptionTagPercentScheduleTaskNamePercent.Click("56;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.BtnAddSubfolderTemplate' at 12;14.", repo.ElproMONITORLogin.BtnAddSubfolderTemplateInfo, new RecordItemIndex(12));
            repo.ElproMONITORLogin.BtnAddSubfolderTemplate.Click("12;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.Save' at 26;19.", repo.ElproMONITORLogin.SaveInfo, new RecordItemIndex(13));
            repo.ElproMONITORLogin.Save.Click("26;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.Close' at 26;16.", repo.ElproMONITORLogin.CloseInfo, new RecordItemIndex(14));
            repo.ElproMONITORLogin.Close.Click("26;16");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
