///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace smokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditDeleteComments recording.
    /// </summary>
    [TestModule("506f3cbe-e870-41a2-8c2b-eeadc72999af", ModuleType.Recording, 1)]
    public partial class EditDeleteComments : ITestModule
    {
        /// <summary>
        /// Holds an instance of the smokeTestRepository repository.
        /// </summary>
        public static smokeTestRepository repo = smokeTestRepository.Instance;

        static EditDeleteComments instance = new EditDeleteComments();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditDeleteComments()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditDeleteComments Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.NavDeviceSettingsIndex' at 102;25.", repo.ElproMONITORLogin.NavDeviceSettingsIndexInfo, new RecordItemIndex(0));
            repo.ElproMONITORLogin.NavDeviceSettingsIndex.Click("102;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.NavApplicationSettingsCommentTemplates' at 81;9.", repo.ElproMONITORLogin.NavApplicationSettingsCommentTemplatesInfo, new RecordItemIndex(1));
            repo.ElproMONITORLogin.NavApplicationSettingsCommentTemplates.Click("81;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.TdTagAT' at Center.", repo.ElproMONITORLogin.TdTagATInfo, new RecordItemIndex(2));
            repo.ElproMONITORLogin.TdTagAT.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.ContentRight.Edit' at 29;19.", repo.ElproMONITORLogin.ContentRight.EditInfo, new RecordItemIndex(3));
            repo.ElproMONITORLogin.ContentRight.Edit.Click("29;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.Text' at 291;25.", repo.ElproMONITORLogin.TextInfo, new RecordItemIndex(4));
            repo.ElproMONITORLogin.Text.Click("291;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}' with focus on 'ElproMONITORLogin.Text'.", repo.ElproMONITORLogin.TextInfo, new RecordItemIndex(5));
            repo.ElproMONITORLogin.Text.PressKeys("{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '' with focus on 'ElproMONITORLogin.Text'.", repo.ElproMONITORLogin.TextInfo, new RecordItemIndex(6));
            repo.ElproMONITORLogin.Text.PressKeys("");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.Save' at 13;17.", repo.ElproMONITORLogin.SaveInfo, new RecordItemIndex(7));
            repo.ElproMONITORLogin.Save.Click("13;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.Close' at 33;15.", repo.ElproMONITORLogin.CloseInfo, new RecordItemIndex(8));
            repo.ElproMONITORLogin.Close.Click("33;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.TdTagAT' at Center.", repo.ElproMONITORLogin.TdTagATInfo, new RecordItemIndex(9));
            repo.ElproMONITORLogin.TdTagAT.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.ContentCenter.Delete' at 20;27.", repo.ElproMONITORLogin.ContentCenter.DeleteInfo, new RecordItemIndex(10));
            repo.ElproMONITORLogin.ContentCenter.Delete.Click("20;27");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
