///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace smokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RecipientProfile recording.
    /// </summary>
    [TestModule("789dc35e-e8fe-4779-91d4-54f7cc50bca3", ModuleType.Recording, 1)]
    public partial class RecipientProfile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the smokeTestRepository repository.
        /// </summary>
        public static smokeTestRepository repo = smokeTestRepository.Instance;

        static RecipientProfile instance = new RecipientProfile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RecipientProfile()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RecipientProfile Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.NavMonitorIndex' at 84;22.", repo.ElproMONITORLogin.NavMonitorIndexInfo, new RecordItemIndex(0));
            repo.ElproMONITORLogin.NavMonitorIndex.Click("84;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.NavDeviceSettingsIndex' at 67;25.", repo.ElproMONITORLogin.NavDeviceSettingsIndexInfo, new RecordItemIndex(1));
            repo.ElproMONITORLogin.NavDeviceSettingsIndex.Click("67;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.NavProfilesRecipientProfiles' at 111;22.", repo.ElproMONITORLogin.NavProfilesRecipientProfilesInfo, new RecordItemIndex(2));
            repo.ElproMONITORLogin.NavProfilesRecipientProfiles.Click("111;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ElproMONITORLogin.ThTagSensorNam'.", repo.ElproMONITORLogin.ThTagSensorNamInfo, new RecordItemIndex(3));
            Validate.Exists(repo.ElproMONITORLogin.ThTagSensorNamInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ElproMONITORLogin.ThTagIOModule'.", repo.ElproMONITORLogin.ThTagIOModuleInfo, new RecordItemIndex(4));
            Validate.Exists(repo.ElproMONITORLogin.ThTagIOModuleInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ElproMONITORLogin.ListDataTableNoFooter.ThTagDelay'.", repo.ElproMONITORLogin.ListDataTableNoFooter.ThTagDelayInfo, new RecordItemIndex(5));
            Validate.Exists(repo.ElproMONITORLogin.ListDataTableNoFooter.ThTagDelayInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ElproMONITORLogin.ListDataTableNoFooter.ThTagLowBatter'.", repo.ElproMONITORLogin.ListDataTableNoFooter.ThTagLowBatterInfo, new RecordItemIndex(6));
            Validate.Exists(repo.ElproMONITORLogin.ListDataTableNoFooter.ThTagLowBatterInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ElproMONITORLogin.ListDataTableNoFooter.ThTagUpperLimi'.", repo.ElproMONITORLogin.ListDataTableNoFooter.ThTagUpperLimiInfo, new RecordItemIndex(7));
            Validate.Exists(repo.ElproMONITORLogin.ListDataTableNoFooter.ThTagUpperLimiInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.ContentCenter.AddNewProfile' at 87;15.", repo.ElproMONITORLogin.ContentCenter.AddNewProfileInfo, new RecordItemIndex(8));
            repo.ElproMONITORLogin.ContentCenter.AddNewProfile.Click("87;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.Name' at 165;19.", repo.ElproMONITORLogin.NameInfo, new RecordItemIndex(9));
            repo.ElproMONITORLogin.Name.Click("165;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.Name' at 235;20.", repo.ElproMONITORLogin.NameInfo, new RecordItemIndex(10));
            repo.ElproMONITORLogin.Name.Click("235;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Ernesto' with focus on 'ElproMONITORLogin.Name'.", repo.ElproMONITORLogin.NameInfo, new RecordItemIndex(11));
            repo.ElproMONITORLogin.Name.PressKeys("Ernesto");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.SendMail' at 6;5.", repo.ElproMONITORLogin.SendMailInfo, new RecordItemIndex(12));
            repo.ElproMONITORLogin.SendMail.Click("6;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.MailToAddress' at 14;19.", repo.ElproMONITORLogin.MailToAddressInfo, new RecordItemIndex(13));
            repo.ElproMONITORLogin.MailToAddress.Click("14;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'e' with focus on 'ElproMONITORLogin.MailToAddress'.", repo.ElproMONITORLogin.MailToAddressInfo, new RecordItemIndex(14));
            repo.ElproMONITORLogin.MailToAddress.PressKeys("e");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'rnest.dogbatse' with focus on 'ElproMONITORLogin.MailToAddress'.", repo.ElproMONITORLogin.MailToAddressInfo, new RecordItemIndex(15));
            repo.ElproMONITORLogin.MailToAddress.PressKeys("rnest.dogbatse");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{RMenu down}{D2}{LControlKey up}{RMenu up}{LControlKey up}elpro.com' with focus on 'ElproMONITORLogin.MailToAddress'.", repo.ElproMONITORLogin.MailToAddressInfo, new RecordItemIndex(16));
            repo.ElproMONITORLogin.MailToAddress.PressKeys("{LControlKey down}{RMenu down}{D2}{LControlKey up}{RMenu up}{LControlKey up}elpro.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.MailToAddress' at 224;11.", repo.ElproMONITORLogin.MailToAddressInfo, new RecordItemIndex(17));
            repo.ElproMONITORLogin.MailToAddress.Click("224;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ElproMONITORLogin.MshtmlHTMLInputElementClass.ButtonTagSendT' at 58;14.", repo.ElproMONITORLogin.MshtmlHTMLInputElementClass.ButtonTagSendTInfo, new RecordItemIndex(18));
            repo.ElproMONITORLogin.MshtmlHTMLInputElementClass.ButtonTagSendT.Click("58;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1200 units.", new RecordItemIndex(19));
            Mouse.ScrollWheel(-1200);
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
