///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace smokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The userRecording recording.
    /// </summary>
    [TestModule("1466c6dd-6547-4c7c-b38a-c59274b7b66d", ModuleType.Recording, 1)]
    public partial class userRecording : ITestModule
    {
        /// <summary>
        /// Holds an instance of the userRepo repository.
        /// </summary>
        public static userRepo repo = userRepo.Instance;

        static userRecording instance = new userRecording();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public userRecording()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static userRecording Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.RowProductLogoContent.Username' at 85;20.", repo.WebDocument192168250180.RowProductLogoContent.UsernameInfo, new RecordItemIndex(0));
            repo.WebDocument192168250180.RowProductLogoContent.Username.Click("85;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin'.", new RecordItemIndex(1));
            Keyboard.Press("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.RowProductLogoContent.Password' at 51;23.", repo.WebDocument192168250180.RowProductLogoContent.PasswordInfo, new RecordItemIndex(2));
            repo.WebDocument192168250180.RowProductLogoContent.Password.Click("51;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password1234' with focus on 'WebDocument192168250180.RowProductLogoContent.Password'.", repo.WebDocument192168250180.RowProductLogoContent.PasswordInfo, new RecordItemIndex(3));
            repo.WebDocument192168250180.RowProductLogoContent.Password.PressKeys("password1234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.RowProductLogoContent.BtnBtnDefaultNgScopeNgIsolateScop' at 27;7.", repo.WebDocument192168250180.RowProductLogoContent.BtnBtnDefaultNgScopeNgIsolateScopInfo, new RecordItemIndex(4));
            repo.WebDocument192168250180.RowProductLogoContent.BtnBtnDefaultNgScopeNgIsolateScop.Click("27;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.Name' at 2;4.", repo.WebDocument192168250180.NameInfo, new RecordItemIndex(5));
            repo.WebDocument192168250180.Name.Click("2;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.MainContentLeft.BtnBtnDefaultNgScopeNgIsolateScop' at 67;30.", repo.WebDocument192168250180.MainContentLeft.BtnBtnDefaultNgScopeNgIsolateScopInfo, new RecordItemIndex(6));
            repo.WebDocument192168250180.MainContentLeft.BtnBtnDefaultNgScopeNgIsolateScop.Click("67;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DownloadAccountReportInternetExplo.ElproUSERRegisterkartengruppe1' at 104;7.", repo.DownloadAccountReportInternetExplo.ElproUSERRegisterkartengruppe1Info, new RecordItemIndex(7));
            repo.DownloadAccountReportInternetExplo.ElproUSERRegisterkartengruppe1.Click("104;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.MainContentLeft.Add' at 24;6.", repo.WebDocument192168250180.MainContentLeft.AddInfo, new RecordItemIndex(8));
            repo.WebDocument192168250180.MainContentLeft.Add.Click("24;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.Cancel' at 17;11.", repo.WebDocument192168250180.CancelInfo, new RecordItemIndex(9));
            repo.WebDocument192168250180.Cancel.Click("17;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.Name' at 1;6.", repo.WebDocument192168250180.NameInfo, new RecordItemIndex(10));
            repo.WebDocument192168250180.Name.Click("1;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.MainContentLeft.Edit' at 6;5.", repo.WebDocument192168250180.MainContentLeft.EditInfo, new RecordItemIndex(11));
            repo.WebDocument192168250180.MainContentLeft.Edit.Click("6;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.Cancel' at 19;11.", repo.WebDocument192168250180.CancelInfo, new RecordItemIndex(12));
            repo.WebDocument192168250180.Cancel.Click("19;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.Name' at 3;8.", repo.WebDocument192168250180.NameInfo, new RecordItemIndex(13));
            repo.WebDocument192168250180.Name.Click("3;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.Groups' at 17;9.", repo.WebDocument192168250180.GroupsInfo, new RecordItemIndex(14));
            repo.WebDocument192168250180.Groups.Click("17;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument192168250180.Name' at 3;7.", repo.WebDocument192168250180.NameInfo, new RecordItemIndex(15));
            repo.WebDocument192168250180.Name.Click("3;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Http192168250183ElproUSERInte' at 5;10.", repo.Http192168250183ElproUSERInte.SelfInfo, new RecordItemIndex(16));
            repo.Http192168250183ElproUSERInte.Self.Click("5;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
