///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace smokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the userRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("7ff3f5a1-83c0-4c74-8124-e105c1ab96d0")]
    public partial class userRepo : RepoGenBaseFolder
    {
        static userRepo instance = new userRepo();
        userRepoFolders.DownloadAccountReportInternetExploAppFolder _downloadaccountreportinternetexplo;
        userRepoFolders.WebDocument192168250180AppFolder _webdocument192168250180;
        userRepoFolders.Http192168250183ElproUSERInteAppFolder _http192168250183elprouserinte;

        /// <summary>
        /// Gets the singleton class instance representing the userRepo element repository.
        /// </summary>
        [RepositoryFolder("7ff3f5a1-83c0-4c74-8124-e105c1ab96d0")]
        public static userRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public userRepo() 
            : base("userRepo", "/", null, 0, false, "7ff3f5a1-83c0-4c74-8124-e105c1ab96d0", ".\\RepositoryImages\\userRepo7ff3f5a1.rximgres")
        {
            _downloadaccountreportinternetexplo = new userRepoFolders.DownloadAccountReportInternetExploAppFolder(this);
            _webdocument192168250180 = new userRepoFolders.WebDocument192168250180AppFolder(this);
            _http192168250183elprouserinte = new userRepoFolders.Http192168250183ElproUSERInteAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7ff3f5a1-83c0-4c74-8124-e105c1ab96d0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DownloadAccountReportInternetExplo folder.
        /// </summary>
        [RepositoryFolder("5218bce4-3aa2-4d97-b38c-19123b76e0f1")]
        public virtual userRepoFolders.DownloadAccountReportInternetExploAppFolder DownloadAccountReportInternetExplo
        {
            get { return _downloadaccountreportinternetexplo; }
        }

        /// <summary>
        /// The WebDocument192168250180 folder.
        /// </summary>
        [RepositoryFolder("9eb0cc0f-b1d8-4c63-87ab-8ff4c592419e")]
        public virtual userRepoFolders.WebDocument192168250180AppFolder WebDocument192168250180
        {
            get { return _webdocument192168250180; }
        }

        /// <summary>
        /// The Http192168250183ElproUSERInte folder.
        /// </summary>
        [RepositoryFolder("aea68ce2-dfac-4cad-be97-732d428d6efc")]
        public virtual userRepoFolders.Http192168250183ElproUSERInteAppFolder Http192168250183ElproUSERInte
        {
            get { return _http192168250183elprouserinte; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class userRepoFolders
    {
        /// <summary>
        /// The DownloadAccountReportInternetExploAppFolder folder.
        /// </summary>
        [RepositoryFolder("5218bce4-3aa2-4d97-b38c-19123b76e0f1")]
        public partial class DownloadAccountReportInternetExploAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _elprouserregisterkartengruppe1Info;

            /// <summary>
            /// Creates a new DownloadAccountReportInternetExplo  folder.
            /// </summary>
            public DownloadAccountReportInternetExploAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DownloadAccountReportInternetExplo", "/form[@title~'^Download\\ Account\\ Report\\ -']", parentFolder, 30000, null, true, "5218bce4-3aa2-4d97-b38c-19123b76e0f1", "")
            {
                _elprouserregisterkartengruppe1Info = new RepoItemInfo(this, "ElproUSERRegisterkartengruppe1", "element[@class='WorkerW']//tabpagelist[@accessiblename='Registerkartenreihe']/tabpage[@accessiblename~'^elproUSER\\ Registerkarteng']", 30000, null, "26a9a737-f722-4446-9f0f-cc033c123c73");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5218bce4-3aa2-4d97-b38c-19123b76e0f1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5218bce4-3aa2-4d97-b38c-19123b76e0f1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ElproUSERRegisterkartengruppe1 item.
            /// </summary>
            [RepositoryItem("26a9a737-f722-4446-9f0f-cc033c123c73")]
            public virtual Ranorex.TabPage ElproUSERRegisterkartengruppe1
            {
                get
                {
                    return _elprouserregisterkartengruppe1Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ElproUSERRegisterkartengruppe1 item info.
            /// </summary>
            [RepositoryItemInfo("26a9a737-f722-4446-9f0f-cc033c123c73")]
            public virtual RepoItemInfo ElproUSERRegisterkartengruppe1Info
            {
                get
                {
                    return _elprouserregisterkartengruppe1Info;
                }
            }
        }

        /// <summary>
        /// The WebDocument192168250180AppFolder folder.
        /// </summary>
        [RepositoryFolder("9eb0cc0f-b1d8-4c63-87ab-8ff4c592419e")]
        public partial class WebDocument192168250180AppFolder : RepoGenBaseFolder
        {
            userRepoFolders.RowProductLogoContentFolder _rowproductlogocontent;
            userRepoFolders.MainContentLeftFolder _maincontentleft;
            RepoItemInfo _nameInfo;
            RepoItemInfo _cancelInfo;
            RepoItemInfo _groupsInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _elproInfo;
            RepoItemInfo _usersInfo;
            RepoItemInfo _name1Info;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _confirmpasswordInfo;
            RepoItemInfo _fullnameInfo;
            RepoItemInfo _groupidInfo;
            RepoItemInfo _pullrightbtnbtndefaultngisolatescInfo;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new WebDocument192168250180  folder.
            /// </summary>
            public WebDocument192168250180AppFolder(RepoGenBaseFolder parentFolder) :
                    base("WebDocument192168250180", "/dom[@page='']", parentFolder, 30000, null, false, "9eb0cc0f-b1d8-4c63-87ab-8ff4c592419e", "")
            {
                _rowproductlogocontent = new userRepoFolders.RowProductLogoContentFolder(this);
                _maincontentleft = new userRepoFolders.MainContentLeftFolder(this);
                _nameInfo = new RepoItemInfo(this, "Name", ".//div[#'borderLayout_eGridPanel']/div[@id='center']/div/div[2]/div[1]//input[@name='name']", 30000, null, "2f933f95-0304-483c-8ff2-b5372a961052");
                _cancelInfo = new RepoItemInfo(this, "Cancel", ".//form[#'contentform']//nav/?/?/div/button[1]/span[@innertext='Cancel']", 30000, null, "b6bb0399-f24f-40af-9a2b-98c84b0c4e12");
                _groupsInfo = new RepoItemInfo(this, "Groups", ".//div[#'side-content']/div[@title='Administration']//a[@href='#/settings/groups']/span[@innertext='Groups']", 30000, null, "f222a656-98bc-4ada-b9e5-4e04747c5367");
                _usernameInfo = new RepoItemInfo(this, "Username", ".//form[#'contentform']/div[2]/div/div[2]/?/?/input[@name='username']", 30000, null, "f0eef3e3-0357-411d-aaf3-a90e51fc09a6");
                _elproInfo = new RepoItemInfo(this, "Elpro", ".//form[#'contentform']/div[2]/div/div[1]/?/?/span[@innertext='elpro']", 30000, null, "ec0a9bcb-80ac-43ba-8f46-a8cb51fd7abb");
                _usersInfo = new RepoItemInfo(this, "Users", ".//div[#'side-content']/div[@title='Administration']//a[@href='#/settings/users']/span[@innertext='Users']", 30000, null, "6b8c55c9-efe0-4431-b885-3f8c43315e07");
                _name1Info = new RepoItemInfo(this, "Name1", ".//input[#'name']", 30000, null, "0166983d-54fc-4d77-8387-f3368e859eae");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "9a56d3ef-cd14-495f-9478-0df976a898a3");
                _confirmpasswordInfo = new RepoItemInfo(this, "ConfirmPassword", ".//input[#'confirmPassword']", 30000, null, "29952efe-1331-4b97-b6a2-5a2062f38bdb");
                _fullnameInfo = new RepoItemInfo(this, "Fullname", ".//input[#'fullname']", 30000, null, "2e543179-6c4d-47e2-917d-b5072beba2f6");
                _groupidInfo = new RepoItemInfo(this, "GroupID", ".//select[#'groupID']", 30000, null, "3b40c0f2-f52b-41f9-8e58-a6cf4b096f98");
                _pullrightbtnbtndefaultngisolatescInfo = new RepoItemInfo(this, "PullRightBtnBtnDefaultNgIsolateSc", ".//form[#'contentform']/div[2]/div/div[3]//button", 30000, null, "7f81c383-604d-4c36-b784-13fe7434d11d");
                _saveInfo = new RepoItemInfo(this, "Save", ".//form[#'contentform']/div[1]/?/?/nav//span[@innertext='Save']", 30000, null, "18d93abc-eb4b-44ff-b186-84a8f14f847f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9eb0cc0f-b1d8-4c63-87ab-8ff4c592419e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9eb0cc0f-b1d8-4c63-87ab-8ff4c592419e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("2f933f95-0304-483c-8ff2-b5372a961052")]
            public virtual Ranorex.InputTag Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("2f933f95-0304-483c-8ff2-b5372a961052")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("b6bb0399-f24f-40af-9a2b-98c84b0c4e12")]
            public virtual Ranorex.SpanTag Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("b6bb0399-f24f-40af-9a2b-98c84b0c4e12")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The Groups item.
            /// </summary>
            [RepositoryItem("f222a656-98bc-4ada-b9e5-4e04747c5367")]
            public virtual Ranorex.SpanTag Groups
            {
                get
                {
                    return _groupsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Groups item info.
            /// </summary>
            [RepositoryItemInfo("f222a656-98bc-4ada-b9e5-4e04747c5367")]
            public virtual RepoItemInfo GroupsInfo
            {
                get
                {
                    return _groupsInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("f0eef3e3-0357-411d-aaf3-a90e51fc09a6")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("f0eef3e3-0357-411d-aaf3-a90e51fc09a6")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Elpro item.
            /// </summary>
            [RepositoryItem("ec0a9bcb-80ac-43ba-8f46-a8cb51fd7abb")]
            public virtual Ranorex.SpanTag Elpro
            {
                get
                {
                    return _elproInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Elpro item info.
            /// </summary>
            [RepositoryItemInfo("ec0a9bcb-80ac-43ba-8f46-a8cb51fd7abb")]
            public virtual RepoItemInfo ElproInfo
            {
                get
                {
                    return _elproInfo;
                }
            }

            /// <summary>
            /// The Users item.
            /// </summary>
            [RepositoryItem("6b8c55c9-efe0-4431-b885-3f8c43315e07")]
            public virtual Ranorex.SpanTag Users
            {
                get
                {
                    return _usersInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Users item info.
            /// </summary>
            [RepositoryItemInfo("6b8c55c9-efe0-4431-b885-3f8c43315e07")]
            public virtual RepoItemInfo UsersInfo
            {
                get
                {
                    return _usersInfo;
                }
            }

            /// <summary>
            /// The Name1 item.
            /// </summary>
            [RepositoryItem("0166983d-54fc-4d77-8387-f3368e859eae")]
            public virtual Ranorex.InputTag Name1
            {
                get
                {
                    return _name1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Name1 item info.
            /// </summary>
            [RepositoryItemInfo("0166983d-54fc-4d77-8387-f3368e859eae")]
            public virtual RepoItemInfo Name1Info
            {
                get
                {
                    return _name1Info;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("9a56d3ef-cd14-495f-9478-0df976a898a3")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("9a56d3ef-cd14-495f-9478-0df976a898a3")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ConfirmPassword item.
            /// </summary>
            [RepositoryItem("29952efe-1331-4b97-b6a2-5a2062f38bdb")]
            public virtual Ranorex.InputTag ConfirmPassword
            {
                get
                {
                    return _confirmpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmPassword item info.
            /// </summary>
            [RepositoryItemInfo("29952efe-1331-4b97-b6a2-5a2062f38bdb")]
            public virtual RepoItemInfo ConfirmPasswordInfo
            {
                get
                {
                    return _confirmpasswordInfo;
                }
            }

            /// <summary>
            /// The Fullname item.
            /// </summary>
            [RepositoryItem("2e543179-6c4d-47e2-917d-b5072beba2f6")]
            public virtual Ranorex.InputTag Fullname
            {
                get
                {
                    return _fullnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Fullname item info.
            /// </summary>
            [RepositoryItemInfo("2e543179-6c4d-47e2-917d-b5072beba2f6")]
            public virtual RepoItemInfo FullnameInfo
            {
                get
                {
                    return _fullnameInfo;
                }
            }

            /// <summary>
            /// The GroupID item.
            /// </summary>
            [RepositoryItem("3b40c0f2-f52b-41f9-8e58-a6cf4b096f98")]
            public virtual Ranorex.SelectTag GroupID
            {
                get
                {
                    return _groupidInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The GroupID item info.
            /// </summary>
            [RepositoryItemInfo("3b40c0f2-f52b-41f9-8e58-a6cf4b096f98")]
            public virtual RepoItemInfo GroupIDInfo
            {
                get
                {
                    return _groupidInfo;
                }
            }

            /// <summary>
            /// The PullRightBtnBtnDefaultNgIsolateSc item.
            /// </summary>
            [RepositoryItem("7f81c383-604d-4c36-b784-13fe7434d11d")]
            public virtual Ranorex.ButtonTag PullRightBtnBtnDefaultNgIsolateSc
            {
                get
                {
                    return _pullrightbtnbtndefaultngisolatescInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The PullRightBtnBtnDefaultNgIsolateSc item info.
            /// </summary>
            [RepositoryItemInfo("7f81c383-604d-4c36-b784-13fe7434d11d")]
            public virtual RepoItemInfo PullRightBtnBtnDefaultNgIsolateScInfo
            {
                get
                {
                    return _pullrightbtnbtndefaultngisolatescInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("18d93abc-eb4b-44ff-b186-84a8f14f847f")]
            public virtual Ranorex.SpanTag Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("18d93abc-eb4b-44ff-b186-84a8f14f847f")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The RowProductLogoContent folder.
            /// </summary>
            [RepositoryFolder("b5759c21-c087-403d-a096-e2af819f6e6b")]
            public virtual userRepoFolders.RowProductLogoContentFolder RowProductLogoContent
            {
                get { return _rowproductlogocontent; }
            }

            /// <summary>
            /// The MainContentLeft folder.
            /// </summary>
            [RepositoryFolder("618da18d-17e5-46b9-80ff-ad5f48c82f59")]
            public virtual userRepoFolders.MainContentLeftFolder MainContentLeft
            {
                get { return _maincontentleft; }
            }
        }

        /// <summary>
        /// The RowProductLogoContentFolder folder.
        /// </summary>
        [RepositoryFolder("b5759c21-c087-403d-a096-e2af819f6e6b")]
        public partial class RowProductLogoContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _btnbtndefaultngscopengisolatescopInfo;

            /// <summary>
            /// Creates a new RowProductLogoContent  folder.
            /// </summary>
            public RowProductLogoContentFolder(RepoGenBaseFolder parentFolder) :
                    base("RowProductLogoContent", ".//form[#'contentform']/div[2]/div/div[2]", parentFolder, 30000, null, false, "b5759c21-c087-403d-a096-e2af819f6e6b", "")
            {
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/input[@name='password']", 30000, null, "2b769400-3d8d-47e1-a621-9bd84d6ce092");
                _usernameInfo = new RepoItemInfo(this, "Username", "?/?/input[@name='username']", 30000, null, "7d0aed61-3707-4eb7-bd53-8fcc8dd4b0c1");
                _btnbtndefaultngscopengisolatescopInfo = new RepoItemInfo(this, "BtnBtnDefaultNgScopeNgIsolateScop", "button", 30000, null, "e9b6358c-5946-4527-9823-c04af57a2fa7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b5759c21-c087-403d-a096-e2af819f6e6b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b5759c21-c087-403d-a096-e2af819f6e6b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("2b769400-3d8d-47e1-a621-9bd84d6ce092")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("2b769400-3d8d-47e1-a621-9bd84d6ce092")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("7d0aed61-3707-4eb7-bd53-8fcc8dd4b0c1")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("7d0aed61-3707-4eb7-bd53-8fcc8dd4b0c1")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The BtnBtnDefaultNgScopeNgIsolateScop item.
            /// </summary>
            [RepositoryItem("e9b6358c-5946-4527-9823-c04af57a2fa7")]
            public virtual Ranorex.ButtonTag BtnBtnDefaultNgScopeNgIsolateScop
            {
                get
                {
                    return _btnbtndefaultngscopengisolatescopInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnDefaultNgScopeNgIsolateScop item info.
            /// </summary>
            [RepositoryItemInfo("e9b6358c-5946-4527-9823-c04af57a2fa7")]
            public virtual RepoItemInfo BtnBtnDefaultNgScopeNgIsolateScopInfo
            {
                get
                {
                    return _btnbtndefaultngscopengisolatescopInfo;
                }
            }
        }

        /// <summary>
        /// The MainContentLeftFolder folder.
        /// </summary>
        [RepositoryFolder("618da18d-17e5-46b9-80ff-ad5f48c82f59")]
        public partial class MainContentLeftFolder : RepoGenBaseFolder
        {
            RepoItemInfo _editInfo;
            RepoItemInfo _addInfo;
            RepoItemInfo _btnbtndefaultngscopengisolatescopInfo;
            RepoItemInfo _reportInfo;
            RepoItemInfo _deleteInfo;

            /// <summary>
            /// Creates a new MainContentLeft  folder.
            /// </summary>
            public MainContentLeftFolder(RepoGenBaseFolder parentFolder) :
                    base("MainContentLeft", ".//div[#'main-content-left']", parentFolder, 30000, null, false, "618da18d-17e5-46b9-80ff-ad5f48c82f59", "")
            {
                _editInfo = new RepoItemInfo(this, "Edit", ".//nav/?/?/div/button[2]/span[@innertext='Edit        ']", 30000, null, "702d027d-7a67-44e3-98d1-6dc686ffa38f");
                _addInfo = new RepoItemInfo(this, "Add", ".//nav/?/?/div/button[3]/span[@innertext='Add        ']", 30000, null, "49907abf-a255-4303-a547-5eade9b502ae");
                _btnbtndefaultngscopengisolatescopInfo = new RepoItemInfo(this, "BtnBtnDefaultNgScopeNgIsolateScop", ".//nav/div[2]/div/button[4]", 30000, null, "0b3dc58b-9046-4c1d-a318-f8457463b928");
                _reportInfo = new RepoItemInfo(this, "Report", ".//nav/?/?/div/button[4]/span[@innertext='Report']", 30000, null, "c9a10954-7d6c-4ea5-945a-859b32d0af50");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//nav/?/?/div/button[1]/span[@innertext='Delete        ']", 30000, null, "30d31451-e5ea-4b6f-b9d7-395fac95cce5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("618da18d-17e5-46b9-80ff-ad5f48c82f59")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("618da18d-17e5-46b9-80ff-ad5f48c82f59")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("702d027d-7a67-44e3-98d1-6dc686ffa38f")]
            public virtual Ranorex.SpanTag Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("702d027d-7a67-44e3-98d1-6dc686ffa38f")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The Add item.
            /// </summary>
            [RepositoryItem("49907abf-a255-4303-a547-5eade9b502ae")]
            public virtual Ranorex.SpanTag Add
            {
                get
                {
                    return _addInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Add item info.
            /// </summary>
            [RepositoryItemInfo("49907abf-a255-4303-a547-5eade9b502ae")]
            public virtual RepoItemInfo AddInfo
            {
                get
                {
                    return _addInfo;
                }
            }

            /// <summary>
            /// The BtnBtnDefaultNgScopeNgIsolateScop item.
            /// </summary>
            [RepositoryItem("0b3dc58b-9046-4c1d-a318-f8457463b928")]
            public virtual Ranorex.ButtonTag BtnBtnDefaultNgScopeNgIsolateScop
            {
                get
                {
                    return _btnbtndefaultngscopengisolatescopInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnDefaultNgScopeNgIsolateScop item info.
            /// </summary>
            [RepositoryItemInfo("0b3dc58b-9046-4c1d-a318-f8457463b928")]
            public virtual RepoItemInfo BtnBtnDefaultNgScopeNgIsolateScopInfo
            {
                get
                {
                    return _btnbtndefaultngscopengisolatescopInfo;
                }
            }

            /// <summary>
            /// The Report item.
            /// </summary>
            [RepositoryItem("c9a10954-7d6c-4ea5-945a-859b32d0af50")]
            public virtual Ranorex.SpanTag Report
            {
                get
                {
                    return _reportInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Report item info.
            /// </summary>
            [RepositoryItemInfo("c9a10954-7d6c-4ea5-945a-859b32d0af50")]
            public virtual RepoItemInfo ReportInfo
            {
                get
                {
                    return _reportInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("30d31451-e5ea-4b6f-b9d7-395fac95cce5")]
            public virtual Ranorex.SpanTag Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("30d31451-e5ea-4b6f-b9d7-395fac95cce5")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }
        }

        /// <summary>
        /// The Http192168250183ElproUSERInteAppFolder folder.
        /// </summary>
        [RepositoryFolder("aea68ce2-dfac-4cad-be97-732d428d6efc")]
        public partial class Http192168250183ElproUSERInteAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Http192168250183ElproUSERInte  folder.
            /// </summary>
            public Http192168250183ElproUSERInteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Http192168250183ElproUSERInte", "/form[@title~'^http://192\\.168\\.250\\.188/el']", parentFolder, 30000, null, true, "aea68ce2-dfac-4cad-be97-732d428d6efc", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aea68ce2-dfac-4cad-be97-732d428d6efc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aea68ce2-dfac-4cad-be97-732d428d6efc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}